version: '3.7'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mysqldata:
    driver_opts:
      o: bind
      type: 'nfs'
      device: /Users/dylanchi/dev/extend-prisma-example/mysqldata
